### ISSUE TITLE
星を消す

### ISSUE THREAD

**Issue by howyi** [voileHQ/front-mock#9]
![star_destroyer](https://user-images.githubusercontent.com/6592938/36597699-49008c3a-18ed-11e8-8378-04d6f760f233.gif)

**Comment by 844196** [comment]
![381397_1](https://user-images.githubusercontent.com/4990822/36599995-63301aba-18f4-11e8-8643-432f842c2570.jpg)

**Comment by howyi** [comment]
https://github.com/voileHQ/front-mock/commit/a115949c5a0257908d1e03a8062a0aa0cc7db90a
![](https://i0.wp.com/i.imgur.com/wgG22Ne.png)
